In [21]:
import numpy as np
import re
import random


In [ ]:
def to_matrix(m,n):
    matrix = np.zeros((m,n))
    return matrix

In [12]:
def fill_matrix(a):
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            a[i][j] = int(input(),16)
    return a

In [84]:
# 遍历
def walk(a):
    start = [0,0]
    end = list(a.shape)
    length = a.shape[0]+a.shape[1]-2
    record = [[],[]]
    for i in range(30):
        sub_record = [[],[]]
        start = [0,0]
        for j in range(length):
            direction = random.randint(0,1) 
            # 1 为向下， 0 为向右
            if (direction == 1 and start[0]+1 <a.shape[0]) or (start[1]+1 >= a.shape[1]):
                start[0] = start[0] + 1
                sub_record[0].append(a[start[0],start[1]])
                sub_record[1].append(1)
            elif direction == 0 or start[0]+1 >= a.shape[0]:
                start[1] = start[1] + 1
                sub_record[0].append(a[start[0],start[1]])
                sub_record[1].append(0)                  
        r = 1
        print(sub_record)
        for k in sub_record[0]:
            r *=k
                
        r = str(r)
        number_of_zero = len(re.findall(r'(0*?)\.0',r)[0])
        if len(record[0]) == 0:
            record[0].append(number_of_zero)
            record[1].append(sub_record[1])
        else:
            if number_of_zero > min(record[0]) or sub_record[1] in record[1]:
                continue
            else:
                record[0] = []
                record[0].append(number_of_zero)
                record[1].append(sub_record[1])
            # 判断几个零
            
            
        
        
    return record

In [85]:
def mian():
    m = int(input())
    n = int(input())
    matrix_a = to_matrix(m,n)
    matrix_a = fill_matrix(matrix_a)
    print(matrix_a)
    record = walk(matrix_a)
    print(record)

In [87]:
mian()

3
3
1
2
3
a
b
c
5
6
7
[[ 1.  2.  3.]
 [10. 11. 12.]
 [ 5.  6.  7.]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[10.0, 11.0, 6.0, 7.0], [1, 0, 1, 0]]
[[2.0, 11.0, 12.0, 7.0], [0, 1, 0, 1]]
[[2.0, 11.0, 12.0, 7.0], [0, 1, 0, 1]]
[[2.0, 3.0, 12.0, 7.0], [0, 0, 1, 1]]
[[10.0, 11.0, 6.0, 7.0], [1, 0, 1, 0]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[2.0, 3.0, 12.0, 7.0], [0, 0, 1, 1]]
[[2.0, 3.0, 12.0, 7.0], [0, 0, 1, 1]]
[[10.0, 11.0, 6.0, 7.0], [1, 0, 1, 0]]
[[2.0, 11.0, 12.0, 7.0], [0, 1, 0, 1]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[10.0, 11.0, 6.0, 7.0], [1, 0, 1, 0]]
[[2.0, 11.0, 12.0, 7.0], [0, 1, 0, 1]]
[[2.0, 11.0, 6.0, 7.0], [0, 1, 1, 0]]
[[10.0, 11.0, 6.0, 7.0], [1, 0, 1, 0]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[10.0, 11.0, 6.0, 7.0], [1, 0, 1, 0]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[10.0, 11.0, 12.0, 7.0], [1, 0, 0, 1]]
[[10.0, 11.0, 12.0, 7.0], [1, 0, 0, 1]]
[[10.0, 5.0, 6.0, 7.0], [1, 1, 0, 0]]
[[2.0, 11.0, 12.0, 7.0], [0, 1, 0, 1]]
[[10.

In [64]:
str(2.0*3.0*12.0*6.0)


'432.0'

In [68]:
q = [[0, 0, 1, 1], [0, 0, 1, 1], [0, 1, 0, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 1, 0, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1]]

TypeError: unhashable type: 'list'